### PR TITLE
Simple Kotlin DSL Property Assignment

### PR DESCRIPTION
**Pull request by niyajali**
https://blog.gradle.org/simpler-kotlin-dsl-property-assignment

### CODE REVIEW

**Comment by niyajali** [comment]
Can We Enable KLib ABI validation
https://github.com/Kotlin/binary-compatibility-validator?tab=readme-ov-file#experimental-klib-abi-validation-support

**Comment by sebaslogen** [comment]
Awesome, thanks for the contribution, I had no idea of this Gradle improvement!
I also like the Klib validation, I'll add it to the backlog, but if you wanna open another PR, you're very welcome!

**Comment by sebaslogen** [comment]
> I would like to but i don't have macOS for multiplatform for that i'm unable to dump klib api if you have than please apply klib validation inside apiValidation block
> 
> ```
> @OptIn(kotlinx.validation.ExperimentalBCVApi::class)
> klib {
>         enabled = true
>     }
> ```
> 
> and dumb klib validation using `apiDump` command and it will generate klib api which is use for verification

No problem, I'll add it soon. Thanks again!

**Comment by sebaslogen** [comment]
Done! https://github.com/sebaslogen/resaca/commit/ee93b12e338b92b177d8c302782b389bd858509b

**Pull request merged**
